/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/**
 * Log level strings according to syslog
 */
export type LogLevel = ("emerg" | "alert" | "crit" | "error" | "warn" | "notice" | "info" | "debug");
