/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

import {LogCodeKey} from './log-code-key.gen'
import {LogCodeStr} from './log-code-str.gen'
import {LogLevel} from './log-level.gen'

export interface Log {
  code_key: LogCodeKey;
  code_str: LogCodeStr;
  /**
   * Log level int according to syslog
   */
  level_int: number;
  level_str: LogLevel;
  /**
   * user message
   */
  user_msg: string;
}
