/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

import {RequestType} from './request-type.gen'
import {ActionType} from './action-type.gen'

export interface JsonPureRequestSchema {
  type: RequestType;
  action_str: ActionType;
  data_type: string;
  request_map: ({
    [k: string]: any;
  } | any[]);
  trans_map?: {
    [k: string]: string;
  };
}
